steps:
  # Step 1 - Pull latest ONNX model from GCS
  - name: 'gcr.io/cloud-builders/gsutil'
    args: ['cp', 'gs://vegdetect-pos-models/models/best_14class_img640.onnx', './api/best_14class_img640.onnx']

  # Step 2 - Build Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - build
      - -t
      - us-central1-docker.pkg.dev/wezard-similarity-score/cloud-run-source-deploy/vegdetect-api:latest
      - ./api

  # Step 3 - Push image to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - push
      - us-central1-docker.pkg.dev/wezard-similarity-score/cloud-run-source-deploy/vegdetect-api:latest

  # Step 4 - Deploy to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    args:
      - gcloud
      - run
      - deploy
      - vegdetect-api
      - --image=us-central1-docker.pkg.dev/wezard-similarity-score/cloud-run-source-deploy/vegdetect-api:latest
      - --region=us-central1
      - --platform=managed
      - --allow-unauthenticated
      - --memory=4Gi
      - --cpu=4
      - --min-instances=1
      - --max-instances=10
      - --set-env-vars=FEEDBACK_BUCKET=vegdetect-pos-models

images:
  - us-central1-docker.pkg.dev/wezard-similarity-score/cloud-run-source-deploy/vegdetect-api:latest

options:
  logging: CLOUD_LOGGING_ONLY
