steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/vegdetect/vegdetect-api', './api']

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/vegdetect/vegdetect-api']

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    args:
      - gcloud
      - run
      - deploy
      - vegdetect-api
      - --image=gcr.io/vegdetect/vegdetect-api
      - --region=us-central1
      - --platform=managed
      - --allow-unauthenticated

images:
  - 'gcr.io/vegdetect/vegdetect-api'

options:
  logging: CLOUD_LOGGING_ONLY
